### ISSUE TITLE
`.yath-persist.json` error message is opaque

### ISSUE THREAD

**Issue by oalders** [Test-More/Test2-Harness#105]
```bash
$ yath run
Could not find .yath-persist.json in current directory, or any parent directories.
```

It took me a while to figure out that (in my case) this actually means "you haven't run `yath start` yet".  I realize that there could be other reasons for this error, but perhaps some kind of a hint about `yath start` could be added to the error message?

**Comment by exodist** [comment]
In the major refactor branch this gives a better message:

`No persistent harness was found for the current path.`

**Comment by oalders** [comment]
Thanks, @exodist!
