### ISSUE TITLE
Can't locate object method "Dumper" via package "Test2::Harness::Event"

### ISSUE THREAD

**Issue by abraxxa** [Test-More/Test2-Harness#109]
Can't locate object method "Dumper" via package "Test2::Harness::Event" at /builds/nac/nac-model-dbic/perl5/lib/perl5/Test2/Harness/Renderer/JUnit.pm line 140, <$fh> line 1.

`use Data::Dumper;` is commented out in line 8 although Dumper is used in production code too.

This happens on t/author-critic.t generated by Dist::Zilla::Plugin::Test::Perl::Critic.

**Comment by abraxxa** [comment]
I just realized that this is Test2-Harness-Renderer-JUnit code, sorry for the incorrect issue!

**Comment by exodist** [comment]
Test2::Harness::Event is part of Test2::Harness, so the bug could still be in this project and not JUnit. I will double check and then fix and/or close.

**Comment by abraxxa** [comment]
Thanks Chad!

**Comment by exodist** [comment]
Latest version of Test2::Harness does not show any occurence of 'Dumper' in Test2::Harness::Event, so pretty sure this is a junit bug.
