### ISSUE TITLE
Unused dependencies

### ISSUE THREAD

**Issue by ppisar** [Test-More/Test2-Harness#111]
When packaging Test2-Harness for Fedora Linux distribution I noticed that following dependencies are declared but not used in the code:

Filter::Util::Call
Symbol
Test2
Test2::Event::V2

These should be moved from runtime to  develop:

Test2::Require::Module

**Comment by ppisar** [comment]
And List::Util is underspecified. META requires 1.44 version while lib/Test2/Harness/Util/TestFile.pm:13 required 1.45.

**Comment by exodist** [comment]
Filter::Util::Call is used by a dep, goto::file. But yeah, the dep should be listed there, not here.
hmm, I am surprised Test2::Event::V2 is not used in the code, like that may mean there is a bug, I have to look into that.

Thanks for the report! I will try to make time to fix this soon.

**Comment by ppisar** [comment]
Test2-Harness-0.001083 added a useless dependency on Test2::Plugin::DBIProfile. While the other two split ones are indeed passed to a perl command arguments, the DBIProfile does not seem to be used anywhere.

**Comment by exodist** [comment]
Not used yet. I am still implementing the feature. I decided to move DBIProfile out before completing the feature so that I could use it without Test2::Harness. When I am done there will be a cli option to enable it.
