### ISSUE TITLE
Time stamps not found in harness_job_launch and harness_job_end

### ISSUE THREAD

**Issue by toddr** [Test-More/Test2-Harness#117]
This case turned out to be because of missing time stamps in Test2::Harness https://github.com/CpanelInc/Test2-Harness-Renderer-JUnit/issues/3

From what I can tell, in 25259186f2af862ea14e8f71438c40d19daba0f2, the time stamps were consolidated but somehow are missing in all events generated by calls to `Test2::Harness::Feeder::Run::_harness_event` which breaks the Renderer trying to read those events.

The hacky fix is this:
```diff
diff --git a/lib/Test2/Harness/Feeder/Run.pm b/lib/Test2/Harness/Feeder/Run.pm
index 3744f3e6..85d3b11c 100644
--- a/lib/Test2/Harness/Feeder/Run.pm
+++ b/lib/Test2/Harness/Feeder/Run.pm
@@ -65,6 +65,7 @@ sub _harness_event {
         job_id     => $job_id,
         event_id   => gen_uuid(),
         run_id     => $run->run_id,
+        stamp      => time,
         facet_data => {@_},
     );
 }
```

**Comment by autarch** [comment]
@exodist ping - this is needed to fix the JUnit renderer.

**Comment by exodist** [comment]
Already talked to toddr about it. Right now in another branch I have a
complete yath refactor almost done. (Code is done, writing docs and tests).
Once the refactor is done I will release it as a fully stable release of
yath. It has a fix for this issue, but not one that can easily be
backported.

**Comment by autarch** [comment]
@exodist Cool. I think for now I can find some workarounds in the JUnit renderer.

**Comment by exodist** [comment]
@toddr Is this fixed in the major_refactor branch? Pretty sure it is, but want your confirmation before I tag it.

**Comment by atoomic** [comment]
this appears to be fixed with the `major_refactor` branch

**Comment by toddr** [comment]
Yes we've tested it and we're good to go.
