### ISSUE TITLE
HARNESS_IS_VERBOSE seems to have gone missing

### ISSUE THREAD

**Issue by rabbiveesh** [Test-More/Test2-Harness#165]
Certain test libraries, like Test2::MojoX, for example, switch their behavior depending on whether the test harness is in verbose mode. It probes the environment variable HARNESS_IS_VERBOSE in order to check this.
This variable does not seem to exist with the new version of yath, so I can no longer see the logs from my mojo tests, which has led me to much sorrow and confusion on my part.

**Comment by exodist** [comment]
This was set by Command.pm in older versions, and was lost in the transition to 1.0, will fix.
