### ISSUE TITLE
yath should let installer pick shebang line

### ISSUE THREAD

**Issue by eilara** [Test-More/Test2-Harness#178]
When set as #!/usr/bin/env perl the install process does not touch the shebang line in the yath script. But people expect the installer to replace it with the Perl used by the installer.

This tiny PR sets shebang on yath to #!/usr/bin/perl, which gets replaced by the installer with the correct perl.

https://github.com/Test-More/Test2-Harness/pull/177

**Comment by exodist** [comment]
Fixed, just uploaded a new release to cpan.
