### ISSUE TITLE
Doesn't work with the latest Test-Simple

### ISSUE THREAD

**Issue by oschwald** [Test-More/Test2-Harness#194]
When using the latest release with the latest `Test-Simple` release, I get:

```
"try_sig_mask" is not exported by the Test2::Util module
```

It appears this function was [moved to another module](https://github.com/Test-More/test-more/commit/20cc150267442fef4857160897d91d90b93382c0#diff-13847904166215a24b4029fba3745101).

**Comment by jjatria** [comment]
See also: https://github.com/Test-More/test-more/issues/872

**Comment by oschwald** [comment]
Thanks! I somehow overlooked that duplicate issue.

**Comment by exodist** [comment]
I am fixing Test::More to once again provide this function. I will be releasing it later this morning.

**Comment by oschwald** [comment]
It appears the fix has been released. Thanks!
