### ISSUE TITLE
the [SKIP!!] non-verbose line doesn't give reason

### ISSUE THREAD

**Issue by rjbs** [Test-More/Test2-Harness#21]
Example!  With `prove`:

```
~$ prove skip-all.pl
skip-all.pl .. skipped: meh
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.05 cusr  0.01 csys =  0.09 CPU)
Result: NOTESTS
```

With `yath`:

```
~$ yath skip-all.pl
[SKIP!!]  =  skip-all.pl

=== ALL TESTS SUCCEEDED ===
```

Also, note the distinction between NOTESTS and ALL TESTS SUCCEEDED.

**Comment by autarch** [comment]
Some of this may have started with my recent changes. I'll investigate.

**Comment by autarch** [comment]
Looks like neither of these things are caused by my changes. I agree they should both be fixed.

**Comment by autarch** [comment]
Hmm, actually, with the latest release I get this:

```
[PASSED]  =  ./skip-all.t passed

=== ALL TESTS SUCCEEDED ===
```
So clearly there's a regression here.
