### ISSUE TITLE
`perldoc yath` or `man yath` doesn't show documentation

### ISSUE THREAD

**Issue by 2shortplanks** [Test-More/Test2-Harness#23]
```
Mark@travis:~$ man yath
No manual entry for yath
Mark@travis:~$ perldoc yath
No documentation found for "yath".
```

I think this is because the yath script hasn't got any pod in it.

**Comment by autarch** [comment]
This is definitely one of those packages welcome situations.

**Comment by autarch** [comment]
Oh, we already have #7 reporting the same thing. I'm closing this one.
