### ISSUE TITLE
"yath test" stuck at "INITIALIZING"...

### ISSUE THREAD

**Issue by bleargh45** [Test-More/Test2-Harness#260]
After updating to a more recent release of Yath, I have seen that running `yath test path/to/test.t` no longer works, but that instead I am stuck at the `INITIALIZING` spinner.

When I run it as `yath test --jobs=1 path/to/test.t` it works just fine, but `yath test path/to/test.t` appears to default to "zero jobs" and acts the same as `yath test --jobs=0 path/to/test.t`.

Going back through various releases to see when this change occurred, it appears to be in v1.000125; versions prior to that work as intended, but 125 and onwards all get stuck at the `INITIALIZING` spinner unless I explicitly specify a number of `--jobs`.

**Comment by exodist** [comment]
What version are you using? I feel like I fixed this bug at some point already, but maybe not.
Can you attach your .yath.rc assuming you have one?
All your examples include `yath test ...` so I am assuming the persistent runner is not in play?

**Comment by bleargh45** [comment]
Am using the `v1.000133` release, on Perl 5.36.  And correct, no persistent runner is in play; this is just `yath test ...` to run a single test on the command line.

Unsure if I have a `.yath.rc` file in play here, but let me go take look upstream in the filesystem and see if there's one sitting around by accident (entirely possible).

Have also been able to determine that if `HARNESS_JOB_COUNT=XXX` is set in the environment, that Yath can then get past the `INITIALIZING` spinner without having `--jobs=XXX` specified on the command line.

**Comment by bleargh45** [comment]
Apologies... digging deeper here, I see that not only is there a `.yath.rc` file present in a parent directory, but that it also loads a custom Plugin which appears to be the problematic one here (removing the custom plugin causes Yath to work as intended, and so I am going to presume that it is the plugin to blame).

Apologies for the noise.
