### ISSUE TITLE
Consider switching away from JSON

### ISSUE THREAD

**Issue by exodist** [Test-More/Test2-Harness#27]
JSON is nice, but JSON encoders simply fail if they encounter an object that lacks the TO_JSON method. This is a problem for event meta-data, and for events that may have arbitrary objects, such as Test2::Event::Exception (Exceptions can be blessed!)

Test2::Harness should really use a serializer that understands perl. Events already work with Storable, that is how the IPC system does it.

I think Test2::Harness should switch to a formatter that sends events over STDOUT using Storable. It will also need to be sure to prevent any other output from hitting the real STDOUT.

Here is an example script that shows how to use storable over a filehandle like this, the Storable docs are not very complete....

```perl
use strict;
use warnings;

use Storable qw/nstore_fd fd_retrieve/;
use Time::HiRes qw/sleep/;
use IO::Handle;

my ($rh, $wh);
pipe($rh, $wh) or die "No pipe!";

my $pid = fork;
die "Could not fork" unless defined $pid;

if ($pid) {
    close($rh);
    sender($wh);
}
else {
    close($wh);
    reader($rh);
}

sub sender {
    my $wh = shift;

    for (1 .. 100) {
        print "Sending: $_\n";
        nstore_fd({num => $_}, $wh) or die "oops";
        $wh->flush;
        sleep 0.02;
    }   

    exit 0;
}

sub reader {
    my $rh = shift;

    while(1) {
        if(my $hashref = fd_retrieve($rh)) {
            print "Got " . $hashref->{num} . "\n";
            exit 0 if $hashref->{num} == 100;
        }   
    }   
}
```

**Comment by autarch** [comment]
I'm not sure exactly what bytes might show up in a serialized Storable object. In particular, can it include `\0` and if so does that cause problems with reading or writing?

If that's an issue, one workaround is use base64 encoding around Storable.

Ultimately it's not really possible to reliably serialize all Perl data. If there is a closure in the things you're storing, you can't really expect to thaw it out in another process and get the same values.

That all said, I don't object to using Storable instead of JSON.

**Comment by exodist** [comment]
The main thing is that all events MUST be serializable via Storable, they simply will not work otherwise due to the IPC system. Switching will make it so that we only have 1 serialization system to think of.

**Comment by exodist** [comment]
@autarch Some of the things you mention as being impossible are actually possible with Storable. Storable is intended to be the perl freeze/thaw. Your example of closures for instance, https://metacpan.org/pod/Storable#CODE-REFERENCES it uses B::Deparse to do its best (not that I think we should rely on that).

**Comment by autarch** [comment]
coderefs != closures

```perl
use v5.24;
use B::Deparse;

my $x = 42;
my $sub = sub { $x + 1 };

say B::Deparse->new->coderef2text($sub);
```

This will give you something like this:

```
{
    use strict;
    no feature ':all';
    use feature ':5.24';
    $x + 1;
}
```

which you obviously cannot thaw in another process.

**Comment by exodist** [comment]
You are correct, and I am obviously too tired to make decisions if I can conflate closure and coderef.
