### ISSUE TITLE
Request: --timer option

### ISSUE THREAD

**Issue by skaji** [Test-More/Test2-Harness#28]
I sometimes use prove's `--timer` option to print elapsed time after each tests. It is useful.
I hope yath has that option too.

**Comment by petdance** [comment]
We rely on the `--timer`/`HARNESS_TIMER` in the harness.

**Comment by exodist** [comment]
This option was added a bit ago (-T)

**Comment by skaji** [comment]
@exodist Thanks!

I compared `yath -T` and `prove --timer`.

* yath https://gist.github.com/skaji/41dc231b6fe9772fffa5b3a9f010d4b3
* prove https://gist.github.com/skaji/348637e2441b97bfe98ff3e691513c84

If yath showed the elapsed time in the same line like prove, it would be easy to understand.

**Comment by exodist** [comment]
Thats a renderer/formatter choice. For the main renderer this is the way I want it displayed, but you could always subclass the renderers to change how it is displayed.

**Comment by skaji** [comment]
Oh, I see, thanks. I'll look into renderers/formatters.

**Comment by exodist** [comment]
I have changed my mind on this. I think it makes sense to postfix the timing data

**Comment by exodist** [comment]
gave it a try, it does not look good, I might revisit later.

**Comment by skaji** [comment]
I'm looking forward to a new version of Test2::Harness 😊
