### ISSUE TITLE
yath injects relative lib and blib directories

### ISSUE THREAD

**Issue by skaji** [Test-More/Test2-Harness#29]
I'm using Test2-Harness-0.001002.

`yath` injects **relative** lib and blib directories, while `prove` injects **absolute** lib and blib directories.
Because now Perl thinks the relative `.` in `@INC` is a vulnerability, so we may want to use absolute paths for `yath` too.

What do you think?

(FYI I found this difference in [this test](https://github.com/skaji/cpm/blob/009594a7830cf3f8bb33b472c82f406d07d3b57b/xt/11_target_perl.t#L13)).
  
## example

test.t
```pl
use strict;
use Test::More tests => 1;
diag $ENV{PERL5LIB};
pass;
```

prove
```
❯ prove -lb test.t
test.t .. # /Users/skaji/lib:/Users/skaji/blib/lib:/Users/skaji/blib/arch
test.t .. ok
```

yath
```
❯ yath test.t
(  DIAG  )  job 01    lib:blib/lib:blib/arch
( PASSED )  job 01    test.t
```

**Comment by autarch** [comment]
I agree that absolute would be better.

**Comment by exodist** [comment]
Yath is supposed to use absolute paths everywhere internally, thanks for
pointing out this mistake.

**Comment by exodist** [comment]
pretty sure this is resolved now
