### ISSUE TITLE
Can leave the terminal in a weird state

### ISSUE THREAD

**Issue by autarch** [Test-More/Test2-Harness#3]
If I hit ctrl-C at the wrong time while the output is happening, it can leave my terminal in a state where I can't see anything that I type. I've seen this with other apps that use the ANSI formatting codes too.

I think one possible fix is to add a `DESTROY` in the EventStream formatter that unconditionally resets the terminal (however one does that).

**Comment by exodist** [comment]
Please check this with 0.000003 which is now on cpan.

**Comment by autarch** [comment]
I'm starting to think that this may actually have nothing to do with the core harness code. Rather, it may be the test suite for this distro that causes the problem. I just noticed that running the tests via prove causes the same problem. I narrowed it down to just running ` prove -lv t/use_harness.t`, but I couldn't find another individual test file that did this.

**Comment by wchristian** [comment]
Ctrl+C isn't even necessary for this, it happened to me by just going `cpan Test2::Harness`.

**Comment by wchristian** [comment]
Didn't happen under Cygwin.
