### ISSUE TITLE
Windows: C:\projects\.yath.rc: No such file or directory

### ISSUE THREAD

**Issue by skaji** [Test-More/Test2-Harness#35]
https://ci.appveyor.com/project/skaji/cpm/build/1.0.52
```
yath test t xt
C:\projects\.yath.rc: No such file or directory at C:/strawberry/perl/site/lib/App/Yath/Util.pm line 47.
Command exited with code 1
```
If you have no intentions to support Windows, please let me know; I will not create issues for Windows.

**Comment by exodist** [comment]
Windows will be suppprted, though some features may be disabled. I will work on windows support once things are a bit more stable in general.
