### ISSUE TITLE
Test passes under prove but fails with yath

### ISSUE THREAD

**Issue by autarch** [Test-More/Test2-Harness#48]
As of 0b037dca3c34d195225998f71baa14d649b30142 in the [Test-Class-Moose repo](https://github.com/houseabsolute/test-class-moose), running `t/process_name.t` under `prove` passes, but fails with `yath`. If I insert a `# HARNESS-NO-STREAM` directive then it will pass under `yath` too. When running `yath -v` I get a number of warnings of the form `Use of uninitialized value in print at /home/autarch/.perlbrew/libs/perl-5.26.1@dev/lib/perl5/Test2/Formatter/Test2.pm line 270.`  The warnings only happen when the no stream directive is enabled.

**Comment by exodist** [comment]
2 bugs here:

1) Formatter/Test2.pm line 270 should not print if @lines is empty
2) For some reason either the stream formatter or the result processor is not understanding the subtests here and is outputing the results both inside and outside the subtests.

**Comment by exodist** [comment]
Can you check if this is still a problem with the latest dev release?

**Comment by autarch** [comment]
This appears to be fixed in the latest release.
