### ISSUE TITLE
Can't correctly preload Devel::Assert::Global with yath

### ISSUE THREAD

**Issue by elcamlost** [Test-More/Test2-Harness#49]
I use assertions from [Devel::Assert](https://metacpan.org/pod/Devel::Assert) and want to enable them during tests.

If I run something like 
```bash
perl -Ilocal/lib/perl5 -Ilib -MDevel::Assert::Global t/path/to/test.t
```

assertions works as expectable, tests failed with message  **Assertions failed**

But if i run something like
```bash
yath -l -Ilocal/lib/perl5 -It -PDevel::Assert::Global t/path/to/test.t
```

assertions don't work, tests pass.

Maybe I incorrectly understand preload feature of Yath or doing something else wrong?
Is there a way to achieve my goal to run test2 tests with yath and enabled assertions?

**Comment by exodist** [comment]
Preload only loads the module (IE require) it does not call ->import() (ie it is not a use statement).

So the module gets preloaded, but its global effect is not applied.

Try:

```yath -PDevel::Assert::Global -MDevel::Assert::Global path/to/test```

the -P will cause it to preload, before fork, the -M will cause import() to be called post-fork before each test. This would also work with just the -M, but the module will have to be loaded after each fork.

There is no pure-preload option that includes import, though you can write a custom Preload module (IE subclasses Test2::Harness::Preload) which loads and imports Devel::Assert::Global. I am not sure if there is any documentation on that yet (work in progress)
