### ISSUE TITLE
Stderr output ends up interleaved with test output in confusing way

### ISSUE THREAD

**Issue by autarch** [Test-More/Test2-Harness#5]
Here's an example:

```
[LAUNCH]  _  t/basic.t
[PARSER]  +  Test2::Harness::Parser::EventStream
[STDERR]  +  Error response:
[ NOTE ]  +  Seeded srand with seed '20160525' from local date.
[STDERR]  +  
[ENCODE]  +  utf8
[STDERR]  +  404 Not Found
[  OK  ]  +  made a new WebService::PivotalTracker object
[STDERR]  +  Client-Date: Wed, 25 May 2016 16:23:11 GMT
[  OK  ]  +  WebService::PivotalTracker::Client=HASH->isa('WebService::PivotalTracker::Client')
[STDERR]  +  
[ DIAG ]  +  Tests were run but no plan was declared and done_testing() was not seen.
[STDERR]  +  
[ DIAG ]  +  Looks like your test exited with 2 after test #2.
[STDERR]  +  For the request:
[STDERR]  +  
[STDERR]  +  GET https://www.pivotaltracker.com/services/v5//stories/120292647
[STDERR]  +  Content-Type: application/json
[STDERR]  +  X-TrackerToken: e99a18c428cb38d5f260853678922e03
[STDERR]  +  
[ PLAN ]  =  No plan was ever set.
[FAILED]  =  t/basic.t

=== FAILURE SUMMARY ===
 * t/basic.t
```

All of the STDERR output is a single die message. It'd be nice to see it all together.

I have no idea how to fix this, however ;)

**Comment by exodist** [comment]
There is a flag to combine STDERR and STDOUT.

    $ yath -m

This will prevent this kind of problem, but it will also make it look like the errors all came from STDOUT.

For a while I tried really hard to make STDOUT/STDERR come in in a reasonable order, but there is no real good way to do it. Essentially we have a race between the test and the harness, will the harness finish reading before the producer finishes writing? If the harness finishes first it switches to the other IO handle.

I am open to improving this, but not if it involves something insane.
