### ISSUE TITLE
Preserve prove -f behavior for STDIN

### ISSUE THREAD

**Issue by toddr** [Test-More/Test2-Harness#59]
Right now this code behaves differently under yath.
```perl
#!perl
use Test::More tests => 1;
ok(!-f STDIN, "stdin");
```

It doesn't have to (at least under UNIX)
this will preserve the behavior and then you don't need to open a temp file for STDIN
```perl
open(STDIN, '<', '/dev/null');
```

**Comment by toddr** [comment]
Not sure if this is brilliant or stupid. feel free to close if the latter.

**Comment by exodist** [comment]
This only works when no STDIN is provided. It is possible to tell yath to provide STDIN at which point it is a file.
