### ISSUE TITLE
yath hangs indefinitely

### ISSUE THREAD

**Issue by toddr** [Test-More/Test2-Harness#70]
I don't have all the details but I'm documenting this as I go.

I've hooked yath into our smoker system which is kicked off from cron. After running all tests, it appears to be hanging. strace shows it in a loop

```
gettimeofday({1524854365, 305527}, NULL) = 0
gettimeofday({1524854365, 305621}, NULL) = 0
read(6, "", 8192)                       = 0
lseek(6, 0, SEEK_SET)                   = 0
lseek(6, 0, SEEK_CUR)                   = 0
read(6, "", 8192)                       = 0
read(7, "", 8192)                       = 0
lseek(7, 0, SEEK_SET)                   = 0
lseek(7, 0, SEEK_CUR)                   = 0
read(7, "", 8192)                       = 0
read(8, "", 8192)                       = 0
lseek(8, 3765478, SEEK_SET)             = 3765478
lseek(8, 0, SEEK_CUR)                   = 3765478
read(8, "", 8192)                       = 0
gettimeofday({1524854365, 306463}, NULL) = 0
gettimeofday({1524854365, 306656}, NULL) = 0
nanosleep({0, 20000000}, NULL)          = 0
```

command line was:

perl yath test -B -k --no-shm --no-blib --no-lib --no-color -PFindBin -PTest::More -PTest::Trap -PTest::MockModule -PTest::Exception -PTest::Deep -PFile::Temp -PTest::Class -j 16 -F /root/20180427-134427/yath_run_1.jsonl

**Comment by toddr** [comment]
During the run, we had 1 unit test that disconnected from the parent process and then had to be killed. I've noticed that killing unit tests seems to have the effect of yath never finishing.

**Comment by toddr** [comment]
I've reproduced this just running from command line. I don't have a root cause yet. Any suggestions on how I can pin down the root cause would be appreciated.

**Comment by toddr** [comment]
What sticks out from a ps tree is that yath-runner is shut down at the point its hanging.

**Comment by toddr** [comment]
After a lot more research we've determined that yath-runner is running like a champ. The issue is yath parsing the job directory in /tmp.

The loop seems to be yath parsing a job dir after it's complete. We have 1 unit test that very reliably (95% of the time) hangs. 

This job runs EVERYTHING in parallel and then comes back with its entire TAP (1200 oks) all at once and then exits. It apears the problem is with Test2::Harness::Job::Dir parsing the stdout and stderr files in order to complete. Some loop is preventing this from ever happening.

```
$>wc -l std*     
 11369 stderr
     0 stdin
 11369 stdout
```

One of the conspicuous things we notice is that some of the esync numbers are out of order. Can you explain what these are and if this sequence of numbers in the file is problematic?

```
T2-HARNESS-ESYNC: 1
T2-HARNESS-ESYNC: 2
T2-HARNESS-ESYNC: 3
T2-HARNESS-ESYNC: 4
T2-HARNESS-ESYNC: 5
T2-HARNESS-ESYNC: 6
T2-HARNESS-ESYNC: 7
T2-HARNESS-ESYNC: 8
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 9
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 10
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 11
T2-HARNESS-ESYNC: 12
T2-HARNESS-ESYNC: 13
T2-HARNESS-ESYNC: 12
T2-HARNESS-ESYNC: 13
T2-HARNESS-ESYNC: 14
T2-HARNESS-ESYNC: 12
T2-HARNESS-ESYNC: 13
```

**Comment by toddr** [comment]
Once the job is done, I presume what remains to do is to parse events.jsonl. Maybe the fix would be to call come sort of final parser for events.jsonl once we know the exit file exists?

**Comment by exodist** [comment]
Try loading Test2::IPC at the vey start of your test, like right after
strict/warnings, but before any test tools. The duplicate numbers int he
sequence tells me that you are forking/threading without turning on Test2's
IPC system.

**Comment by toddr** [comment]
That's basically exactly what Test::Parallel does. I'm sure we could make a generic example that craps out consistently with this. let me see what I can do.

**Comment by toddr** [comment]
My bad. The test in question is using MCE which I've never heard of. Converting to Test::Parallel which we've never had trouble with in the past.

**Comment by toddr** [comment]
FYI loading Test2::IPC does not seem to counteract MCE.

**Comment by toddr** [comment]
MCE was indeed the problem. I'll work on getting a simplified test soon.

**Comment by toddr** [comment]
I also caused a similar hang as a result of b1ccece913fc49f79c79904a4cd526b0837cc1ca

After Testing, it appears the problem is that Crypt::URandom is holding an open file handle permanently to /dev/urandom. On fork, this appears to be triggering unexpected T2-HARNESS-ESYNC messages that hangs things? I've tested that getting rid of the package level file handle that doesn't go away until global destruction solves the problem. 

I can probably fix Crypt::URandom. However I think this is probably a more general problem that will eventually need to be addressed?

**Comment by exodist** [comment]
If we can address it generically in the harness we should.

**Comment by exodist** [comment]
Is this still an issue with the rework from major_refactor?

**Comment by toddr** [comment]
Given I re-worked the test. I'm not sure I can say. Lets close this for now and I'll re-open if I find a failing test again.
