### ISSUE TITLE
yath fails with async option set as case default

### ISSUE THREAD

**Issue by vrurg** [Test-More/Test2-Harness#79]
yath fails due to malformed JSON when Test2::Tools::Spec is used with

```
spec_defaults case => ( async => 1 );
```
and when yath is run with following args:

```
yath test -Ilib -v -j 4 t/010-filter.t
```

Unfortunately, I cannot reproduce the problem in a simpler test suit other than one from https://github.com/vrurg/MooX-AttributeFilter – t/010-filter.t It doesn't have the async option by default but it shouldn't be a problem to add one, I hope.

Here is the output of the command above:

[yath_out.txt](https://github.com/Test-More/Test2-Harness/files/2120770/yath_out.txt)

**Comment by exodist** [comment]
@vrurg Can you check and see if this is still an issue when using the major_refactor branch?

**Comment by vrurg** [comment]
Unfortunately, I can't currently remember all the details of what I was doing at the time. But following own description I don't get the problem reproduced.
