### ISSUE TITLE
Fails with List::Util < 1.44

### ISSUE THREAD

**Issue by andk** [Test-More/Test2-Harness#82]
Diagnostics: "uniq" is not exported by the List::Util module

Seen in: http://www.cpantesters.org/cpan/report/96806433

**Comment by exodist** [comment]
Just merged a fix for this, next release will have it.

**Comment by andk** [comment]
1.33 is too low.

**Comment by andk** [comment]
Test2-Harness-0.001068.Makefile.PL declares 1.33 as requirement.
