### ISSUE TITLE
perl 5.8 compatibility

### ISSUE THREAD

**Issue by skaji** [Test-More/Test2-Harness#89]
dist.ini states that minimum perl version is 5.8.9.
https://github.com/Test-More/Test2-Harness/blob/709183942f76ce0483405bec6080479220b4dd52/dist.ini#L41

But some modules use `//` which is introduced in perl 5.10:
https://github.com/Test-More/Test2-Harness/blob/709183942f76ce0483405bec6080479220b4dd52/lib/App/Yath/Command.pm#L753
https://github.com/Test-More/Test2-Harness/blob/709183942f76ce0483405bec6080479220b4dd52/lib/Test2/Formatter/Stream.pm#L88

**Comment by aeruder** [comment]
Whoops, my bad.  Thanks.
